name: build
on:
  push:
    branches:
      - main
      - autobuild
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./autobuild
    steps:
      - uses: actions/checkout@v3
      - name: Install 7zip
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install 7zip.install
      - name: "Download old-src.trunk.r687.20150728.7z"
        shell: powershell
        run: "Invoke-WebRequest -Uri https://bits.sigpipe.me/mirrors/file.opennt.net/release/obsolete/sr687/old-src-sr687.7z -OutFile old-src-sr687.7z"