name: build
on:
  push:
    branches:
      - main
      - autobuild
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./autobuild
    steps:
      - uses: actions/checkout@v3
      - name: Install 7zip
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install 7zip.install